
-- SCHEMA: comments + votes + (optional) rate limit helper

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  username text unique,
  avatar_url text,
  created_at timestamptz default now()
);

create table if not exists public.comments (
  id bigint generated by default as identity primary key,
  page_id text not null,
  author_id uuid,
  author_name text,
  body text not null,
  deleted boolean not null default false,
  created_at timestamptz default now()
);
create index if not exists comments_page_id_idx on public.comments(page_id);
create index if not exists comments_created_at_idx on public.comments(created_at desc);

create table if not exists public.comment_votes (
  id bigint generated by default as identity primary key,
  comment_id bigint not null references public.comments(id) on delete cascade,
  voter_id uuid,
  voter_fingerprint text,
  value smallint not null check (value in (-1, 1)),
  created_at timestamptz default now(),
  constraint one_vote_per_user unique (comment_id, voter_id),
  constraint one_vote_per_fingerprint unique (comment_id, voter_fingerprint)
);
create index if not exists comment_votes_comment_id_idx on public.comment_votes(comment_id);

create or replace view public.comment_vote_counts as
select
  c.id as comment_id,
  coalesce(sum(case when v.value = 1 then 1 else 0 end),0) as likes,
  coalesce(sum(case when v.value = -1 then 1 else 0 end),0) as dislikes
from public.comments c
left join public.comment_votes v on v.comment_id = c.id
where c.deleted = false
group by c.id;

alter table public.profiles enable row level security;
alter table public.comments enable row level security;
alter table public.comment_votes enable row level security;

create policy if not exists "read profiles" on public.profiles for select using (true);
create policy if not exists "insert own profile" on public.profiles for insert with check (auth.uid() = id);
create policy if not exists "update own profile" on public.profiles for update using (auth.uid() = id) with check (auth.uid() = id);

create policy if not exists "read comments" on public.comments for select using (deleted = false);
create policy if not exists "insert own comment" on public.comments for insert with check ((author_id is not null and author_id = auth.uid()));
create policy if not exists "update own comment" on public.comments for update using (author_id = auth.uid()) with check (author_id = auth.uid());

create policy if not exists "read votes" on public.comment_votes for select using (true);
create policy if not exists "upsert own vote" on public.comment_votes for all using (voter_id = auth.uid()) with check (voter_id = auth.uid());

DO $$ BEGIN
  BEGIN EXECUTE 'alter publication supabase_realtime add table public.comments'; EXCEPTION WHEN others THEN NULL; END;
  BEGIN EXECUTE 'alter publication supabase_realtime add table public.comment_votes'; EXCEPTION WHEN others THEN NULL; END;
END $$;
